name         'smarchive-scala'
version      '0.2.0'
author       'Jochen Schalanda'
license      'Apache 2.0'
project_page 'https://github.com/gini/puppet-scala'
source       'https://github.com/gini/puppet-scala'
summary      'Puppet module for managing Scala'
description  'This module installs and manages the Scala programming environment. Check README.md for details.'
dependency   'smarchive/archive', '>= 0.1.0'
